### ISSUE TITLE
not working please see attached picture,

### ISSUE THREAD

**Issue by fisforfaheem** [The-ring-io/flutter_phoenix#24]
![image](https://user-images.githubusercontent.com/35878088/186664168-59ab4edd-26c6-42f9-8bcb-d699f7c9541e.png)

i want the whole app to restart, and all my controllers but it stays same and this is shown in te log

**Comment by Miiite** [comment]
If this issue is still occuring, could you provide a reproduction project ?

**Comment by fisforfaheem** [comment]
yes, I am unable to use this to reset or restart my app or widget in flutter web can you see if you can do that as well!

**Comment by Miiite** [comment]
That wasn't explicitely stated in the docs before, but `flutter_phoenix` has never been tested on the web, and that's not really the goal of the library since on the web you could reload the state of your application by loading a specific URL (at least in theory).

The `web` badge was removed a few days ago to clarify the state of the library.

**Comment by fisforfaheem** [comment]
Thanks for clarifying...however, can you please explore that as well, for
web.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
03/23/23,
03:56:48 PM
